console.log('////MODULE EXPORTS////', `\n`, module.exports, `\n`)
console.log('////EXPORTS////', `\n`, exports, `\n`)
console.log('////REQUIRE////', `\n`, require, `\n`)
console.log('////FILENAME////', `\n`, __filename, `\n`)
console.log('////DIRNAME////', `\n`, __dirname, `\n`)
console.log('////ARGUMENTS////', `\n`, arguments)